modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
mixinConfigs=["sweet_charm_o_mine.mixins.json"]

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId = "gunswithoutroses"
    versionRange = "[1.20.1-2.4.0,)"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "curios"
    versionRange = "[5.14.1,)"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"